spring:
  boot:
    admin:
      client:
        url: http://192.168.100.110:8184

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info