spring:
  application:
    name: isystem-service-fileupload
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  port: 8505

# 分布式文件系统DFS配置
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 500
    height: 500
  web-server-url: 192.168.100.110:8888/
  trackerList: 192.168.100.110:22122

# 阿里云oss配置
oss:
  #暂时的外网节点, 如果发布到线上环境, 只要阿里云ESC服务器与oss服务器同一地域, 可以使用内网节点
  end-point: oss-cn-qingdao.aliyuncs.com
  access-keyId: LTAIoc5iy7rzY5oF
  access-keySecret: B7INLs3bwisLsUjcAcwNWx0RU4zCKI
