spring:
  application:
    name: isystem-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yk-isystem20191202?characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 6000

server:
  port: 8769

#api:
#  access-control: true
#  check-sign: false
#  api-debug: true
#  permitAll:

ribbon:
  #请求连接的超时时间
  ConnectTimeout: 2000
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #请求处理的超时时间
  ReadTimeout: 5000

zuul:
  #是否开启路由重试
  retryable: true
  add-host-header: true
  host:
    connect-timeout-millis: 10000
    max-per-route-connections: 500
    max-total-connections: 1000
    socket-timeout-millis: 60000
  ignored-services: '*'
  ratelimit:
    behind-proxy: true
    enabled: true
    key-prefix: cloud_rate_limit
    repository: REDIS
    add-response-headers: false
  semaphore:
    max-semaphores: 1000
  sensitive-headers: ''

api:
  #动态权限控制
  access-control: true
  #校验参数签名
  check-sign: false
  #接口调试,生产环境设为false
  api-debug: true
  # 始终放行
  permit-all:
    - /*/login/**
    - /*/logout/**
    - /*/oauth/**
  # 忽略权限鉴定
  authority-ignores:
    - /*/authority/granted/me
  # 签名忽略
  sign-ignores:
    - /**/login/**


