spring:
  application:
    name: isystem-zuul

server:
  port: 8769

api:
  access-control: true
  check-sign: false
  api-debug: true
  permit-all: /*/api/login/**, /*/api/logout/**, /*/oauth/**, /actuator/health, /actuator/info, /*/api/generate/generateCode/**

ribbon:
  #请求连接的超时时间
  ConnectTimeout: 2000
  #对当前实例的重试次数
  MaxAutoRetries: 10
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 10
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #请求处理的超时时间
  ReadTimeout: 5000

zuul:
  #是否开启路由重试
  retryable: true
  add-host-header: true
  host:
    connect-timeout-millis: 10000
    max-per-route-connections: 500
    max-total-connections: 1000
    socket-timeout-millis: 60000
  ignored-services: '*'
  ratelimit:
    behind-proxy: true
    enabled: true
    key-prefix: cloud_rate_limit
    repository: REDIS
    add-response-headers: false
  semaphore:
    max-semaphores: 1000
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken

#api:
#  access-control: true
#  check-sign: false
#  api-debug: true
#  permit-all:
#    -/*/login/**
#    -/*/logout/**
#    -/*/oauth/**
#  authority-ignores:
#    -/*/authority/granted/me
#  sign-ignores:
#    -/**/login/**

#oauth2配置
#authorization-param:
#  client-id: 123456 #客户端id
#  secret: 123456 #客户端秘钥
#  authorized-grant-types: password #授权类型
#  token-expire: 10000 #token过期时间
#  token-refresh: 1500 #token刷新时间

isystem:
  client:
    oauth2:
      auth:
        client-id: 7gBZcbsC7kLIWCdELIl8nxcs #客户端id
        secret: 0osTIhce7uPvDKHz6aa67bhCukaKoYl4 #客户端秘钥
        authorized-grant-types: password #授权类型
        token-expire: 10000 #token过期时间
        token-refresh: 1500 #token刷新时间


