spring:
  redis:
    database: 0 #Redis数据库索引(默认为0)
    host: 47.104.29.22 #Redis服务器地址
    port: 6379 #连接端口
    password: 123456 #连接密码(默认为空)
    pool:
      max-active: 200 #连接池最大连接数
      max-wait: -1 #连接池最大阻塞等待时间(负值标识没有限制)
      max-idle: 10 #连接池最大空闲连接
      min-idle: 0 #连接池最小空闲连接
    timeout: 1000 #超时时间(ms)