spring:
  boot:
    admin:
      client:
        url: http://localhost:8184

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info