spring:
  application:
    name: isystem-service-fileupload
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yk-isystem20191202?characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 6000


server:
  port: 8505

# 分布式文件系统DFS配置
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  reqHost: 192.168.100.110
  reqPort: 8888
  trackerList:
    - 192.168.100.110:22122